services:

  nginx:
    build:
      context: .
      dockerfile: ./nginx/docker/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "83:80"
    volumes:
      - "./:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - db
    networks:
      - client_net

  # Container for Laravel
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - "./:/var/www/html"
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_DATABASE=clientdb"
      - "DB_USERNAME=clientroot"
      - "DB_PASSWORD=secret!132"
    command: bash -c "composer install && cp .env.example .env && php artisan key:generate && php-fpm"
    depends_on:
      - db
    networks:
      - client_net

  # Container for MariaDB
  db:
    image: mariadb:latest
    restart: always
    ports:
      - "3315:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: clientdb
      MYSQL_USER: clientroot
      MYSQL_PASSWORD: secret!132
    command:
      [
        '--default-authentication-plugin=mysql_native_password',
        '--init-file=/docker-entrypoint-initdb.d/init.sql'
      ]
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - client_net

networks:
  client_net:
